
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 05 09:59:59 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 49;
  public static final int LBRACKET = 22;
  public static final int GREATER_OR_EQUAL = 34;
  public static final int CONST = 3;
  public static final int NOT_EQUAL = 32;
  public static final int LPAREN = 24;
  public static final int GREATER = 33;
  public static final int SEMI = 26;
  public static final int CONTINUE = 10;
  public static final int MINUS = 40;
  public static final int LESS = 35;
  public static final int RPAREN = 25;
  public static final int AND = 46;
  public static final int LESS_OR_EQUAL = 36;
  public static final int OR = 45;
  public static final int COMMA = 27;
  public static final int CLASS = 16;
  public static final int INC = 37;
  public static final int DIV = 42;
  public static final int PLUS = 39;
  public static final int ASSIGN = 30;
  public static final int IF = 5;
  public static final int IS_EQUAL = 31;
  public static final int THIS = 17;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 23;
  public static final int SUPER = 19;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int MOD = 43;
  public static final int IDENT = 47;
  public static final int BREAK = 9;
  public static final int VOID = 15;
  public static final int COLON = 28;
  public static final int QQ = 44;
  public static final int LBRACE = 20;
  public static final int ELSE = 6;
  public static final int ENUM = 18;
  public static final int READ = 12;
  public static final int WHILE = 8;
  public static final int RBRACE = 21;
  public static final int EXTENDS = 4;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 50;
  public static final int DEC = 38;
  public static final int PRINT = 13;
  public static final int DO = 7;
  public static final int NUMBER_CONST = 48;
}

