
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 30 12:34:55 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 24;
  public static final int GREATER_OR_EQUAL = 36;
  public static final int CHAR = 51;
  public static final int CONST = 3;
  public static final int NOT_EQUAL = 34;
  public static final int GREATER = 35;
  public static final int LPAREN = 26;
  public static final int SEMI = 28;
  public static final int CONTINUE = 10;
  public static final int MINUS = 42;
  public static final int LESS = 37;
  public static final int INSTANCEOF = 15;
  public static final int RPAREN = 27;
  public static final int AND = 48;
  public static final int LESS_OR_EQUAL = 38;
  public static final int OR = 47;
  public static final int BOOL = 52;
  public static final int COMMA = 29;
  public static final int CLASS = 18;
  public static final int INC = 39;
  public static final int DIV = 44;
  public static final int PLUS = 41;
  public static final int ASSIGN = 32;
  public static final int IF = 5;
  public static final int IS_EQUAL = 33;
  public static final int THIS = 19;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 25;
  public static final int SUPER = 21;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 43;
  public static final int NUMBER = 50;
  public static final int MOD = 45;
  public static final int IDENT = 49;
  public static final int BREAK = 9;
  public static final int VOID = 17;
  public static final int COLON = 30;
  public static final int QQ = 46;
  public static final int LBRACE = 22;
  public static final int ELSE = 6;
  public static final int ENUM = 20;
  public static final int READ = 12;
  public static final int GOTO = 14;
  public static final int WHILE = 8;
  public static final int RBRACE = 23;
  public static final int EXTENDS = 4;
  public static final int PROG = 2;
  public static final int DEC = 40;
  public static final int PRINT = 13;
  public static final int DO = 7;
}

